name: chessarray
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9        # TensorFlow 2.x works well with Python 3.9
  - numpy=1.22        # Match with TensorFlow compatibility
  - scipy
  - pandas=1.4
  - scikit-learn
  - scikit-image
  - joblib
  - pyserial
  - seaborn
  - statsmodels
  - fastapi
  - uvicorn
  - opencv            # Specify version if needed, e.g., opencv=4.5.5
  - jupyter           # Includes Jupyter Notebook
  - matplotlib 
  - pip               # Ensure pip is installed for extra dependencies
  - pip:
      - python-chess
      - stockfish